### ISSUE TITLE
Question on usage for serialization/deserialization

### ISSUE THREAD

**Issue by kostenko** [kantega/kson#1]
Hey guys, I was searching for a better way of solving my JSON serialization/deserialization issue (even posted a [StackOverflow question](https://stackoverflow.com/questions/47169695/java-json-library-supporting-getting-and-setting-deep-values-without-schema)) and found your library. Seems like it could solve my problem without involving terrible typical Java POJO-oriented annotation-driven techniques with Jackson and JsonPath (see my workaround-solution in the StackOverflow question I posted).
The problem I'm trying to solve is that I'm calling some third-party API service which spits out a huge JSON with an enormous number of fields and embedded entities. In my app, I need fewer fields than there are embedded entities in that JSON, and I just don't want to model all that junk in my codebase and I'd prefer to map that big thing to my little flat POJO with 7 fields and use it across my entire app and then serialize it back — also into a little JSON but preserving their schema — only when calling that endpoint.
Do I understand correctly, that with your library the approach would be to create a decoder for my flat class, let's say `littlePojoDecoder` — seems like I can have it as a static member of my POJO class (can't I?), and for serialization I can just use `jObj` and `field` in a static mapping method?
Thanks.

**Comment by prange** [comment]
Hi, sorry for the delay. You are in luck there is a limit of 7 fields when you make codecs using jObj+field static mapping.  When i write codecs i usually have them as static fields in an a Codec class, but keeping the codec in your domain class is also a good choice. (Thats the beauty of keeping the codecs as simple functions, you can have them wherever you like) There are som examples of simple codecs you can use a blueprint. let me know if you have any progress.

**Comment by prange** [comment]
I also gave an example on Stackoverflow. You basically have to options with kson: 
1) You can make decoders. They are meant to map between the json and your domain objects. It is of course the tidiest when the json and your domain model have a simlar structure, but you can build arbitrary deep nestings when you define your mapping. To be honest i have not tried that myself.
2) You can read the json values you need using the JsonResult type, and manually build your domain with those values. I think the examples can point you in the right direction. If you need more help feel free to ask!

**Comment by prange** [comment]
I added an example in the test folder called `DeepNestedDecoderExample`. It uses mapping (as in java.util.Stream if you are familiar) to convert the nested data to a domain object.

**Comment by kostenko** [comment]
Thank you! At the moment I have to move forward with the implementation of the actual task I've been working on, but once I move it forward I'm going to get back to this serialization/deserialization problem and will try the approach from DeepNestedDecoderExample.
Although, I feel like I might go with implementing my own monadic type for this purpose. The reason is that my goal was to avoid schema declaration by any mean, as it can be reconstructed by composing all lens paths into one object, but decoders and encoders are kinda an equivalent of a schema declaration.

**Comment by prange** [comment]
Yes the codec approach is a schema declaration. But kson has lenses too, or you can use the JsonResult monad to extract each values manually. (Take a look at the LensExample)
